services:
  - type: web
    name: campus-hire-api
    runtime: node
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: JWT_COOKIE_EXPIRE
        value: 7
      - key: FRONTEND_URL
        sync: false
